namespace: "infrabuildxyz"
name: "disconnectedinfra"
version: "0.0.1"
readme: "README.md"
authors:
    - "Holden Fenner hfenner@redhat.com"
license:
    - "APACHE2.0"
tags:
    - cyber
    - infrastructure
    - disconnected
repository: "https://www.github.com/infrabuildxyz/disconnectedinfra"