rhel8:
  variables:
    username: !unsafe '{{ env `VMWARE_USER` }}'
    password: !unsafe '{{ env `VMWARE_PASSWORD` }}'
    vcenter_server: "{{ vsphere.vcenter_server }}"
    cluster: "{{ vsphere.cluster }}" 
    datacenter: "{{ vsphere.datacenter }}"
    datastore: "{{ vsphere.datastore }}"
    folder: "{{ vsphere.folder }}"
    network: "{{ vsphere.network }}"
    vm_name: rhel8
    ddmmyy: "{{ lookup('pipe','date +%d%m%y') }}"
    ssh_username: root
    ssh_password: thisisabadpassword
    iso_url: http://artifact.infrabuild.xyz/iso/rhel-8.2-x86_64-dvd.iso
    rhsm_username: rhsmusername
    rhsm_password: !unsafe '{{ env `RHSM_PASSWORD` }}'
    rhsm_pool_id: uuidforpoolid
    output_directory: "{{ artifact_directory }}"
  sensitive-variables:
    - password
    - rhsm_password
  builders:
    - type: vsphere-iso
      CPUs: 2
      RAM: 4096
      RAM_reserve_all: true
      username: !unsafe '{{ user `username` }}'
      password: !unsafe '{{ user `password` }}'
      vcenter_server: !unsafe '{{ user `vcenter_server` }}'
      cluster: !unsafe '{{ user `cluster` }}'
      datacenter: !unsafe '{{ user `datacenter` }}'
      datastore: !unsafe '{{ user `datastore` }}'
      folder: !unsafe '{{ user `folder` }}'
      disk_controller_type: pvscsi
      firmware: bios
      boot_wait: 10s
      boot_order: disk,cdrom
      http_directory: http
      boot_command:
      - !unsafe <tab> inst.sshd inst.text inst.ks=http://{{ .HTTPIP }}:{{ .HTTPPort}}/rhel8ks.cfg<enter><wait>
      guest_os_type: centos7_64guest
      insecure_connection: "true"
      iso_checksum: none
      iso_urls:
      - !unsafe '{{ user `iso_url` }}'
      network_adapters:
        - network: !unsafe '{{ user `network` }}'
          mac_address: "{{ '00:50:56:A8' | random_mac }}"
          network_card: vmxnet3
      vm_name: !unsafe '{{ user `vm_name` }}'
      ssh_username: !unsafe '{{ user `ssh_username` }}'
      ssh_password: !unsafe '{{ user `ssh_password` }}'
      notes: !unsafe 'SSH Username {{ user `ssh_username` }}\nSSH Password {{ user `ssh_password` }}'
      storage:
        - disk_size: 40906
          disk_thin_provisioned: true
      export:
        force: true
        output_directory: !unsafe '{{ user `output_directory` }}'
        name: !unsafe '{{ user `vm_name` }}-{{ user `ddmmyy` }}'
  provisioners:
  - type: ansible
    playbook_file: playbook.yml
    extra_arguments:
    - --extra-vars
    - !unsafe 'rhsm_username={{ user `rhsm_username` }} rhsm_password={{ user `rhsm_password` }} rhsm_pool_id={{ user `rhsm_pool_id` }}'
