---
- name: Template file out
  copy:
    content: "{{ vcsa_esxi }}"
    dest: "{{ config_directory }}/{{ vcsa_config_file_name }}"

- name: Download VCSA ISO
  get_url:
    url: "{{ vcsa_iso_url }}" 
    dest: /mnt/vcsa.iso
  become: yes

- name: Mount DVD's
  mount:
    path: /mnt/vcsa
    src: /mnt/vcsa.iso
    fstype: iso9660
    opts: ro,noauto
    state: mounted
  become: true

- name: Install libsnl to use OVFTool on Enterprise Linux
  yum:
    name: libnsl
    state: latest
  become: true

- name: Install VCSA
  command: "/mnt/vcsa/vcsa-cli-installer/lin64/vcsa-deploy install --accept-eula {{ config_directory }}/{{ vcsa_config_file_name }}"

- ansible.builtin.pause:
    minutes: 5

- name: Add a datacenter
  vmware_datacenter:
    hostname: "{{ vcsa_build.vcenter_ip }}"
    username: "administrator@{{ vcsa_build.vcenter_system_name }}" 
    password: "{{ vcsa_build.vcenter_password }}" 
    validate_certs: no
    datacenter_name: Datacenter
    state: present

- name: Add an ESXi host
  vmware_host:
    hostname: "{{ vcsa_build.vcenter_ip }}"
    username: "administrator@{{ vcsa_build.vcenter_system_name }}" 
    password: "{{ vcsa_build.vcenter_password }}" 
    validate_certs: no
    datacenter_name: Datacenter
    folder: /Datacenter/host
    esxi_hostname: "{{ vcsa_build.esxi_hostname }}"
    esxi_username: root
    esxi_password: "{{ vcsa_build.esxi_password }}"
    state: present
