#jinja2:variable_start_string:'[%', variable_end_string:'%]', trim_blocks: False
---
- name: Fully Update System
  hosts: default
  become: true

  tasks:
    - name: Register to Red Hat 
      redhat_subscription:
        state: present
        username: "{{ rhsm_username }}"
        password: "{{ rhsm_password }}"
        pool_ids: "{{ rhsm_pool_id }}"
      when: ansible_distribution == 'RedHat'

    - name: Install key packages
      yum:
        name:
        - vim
        - git
        - open-vm-tools
        state: latest

    - name: Update all the packages
      yum:
        name: '*'
        state: latest

    - name: Cleanup script for Red Hat
      shell: |
        subscription-manager unsubscribe --all
        subscription-manager unregister
        subscription-manager clean
        rm -rf /var/log/rhsm/*
        rm -rf /tmp/*
        rm -rf /var/cache/yum/*
        rm -rf /etc/ssh/ssh_host_*
        dd if=/dev/zero of=/EMPTY bs=1M
        rm -f /EMPTY
        sync && sync
      when: ansible_distribution == 'RedHat'

    - name: Cleanup script for CentOS
      shell: |
        rm -rf /tmp/*
        rm -rf /var/cache/yum/*
        rm -rf /etc/ssh/ssh_host_*
        dd if=/dev/zero of=/EMPTY bs=1M
        rm -f /EMPTY
        sync && sync
      when: ansible_distribution == 'CentOS'
