config_directory: /build_config
artifact_directory: /build_artifact
explode_directory: /build_explode
artifact_server: http://artifact.infrabuild.xyz
vsphere:
  vcenter_server: vcenter.infrabuild.xyz
  cluster: main
  datacenter: Datacenter
  datastore: Datastore1
  folder: Templates
  network: BUILDNET
  username: administrator@vsphere.infrabuild.xyz
  password: DunderMifflin1234$
  esxi_hostname: 192.168.5.202
rhsm:
  username: redhat_username
  password: BadPassword1234$
  pool_id: 769a77667d83243s769a77667d83243s
env:
  VMWARE_PASSWORD: "{{ vsphere.password }}"
  RHSM_PASSWORD: "{{ lookup('env', 'RHSM_PASSWORD') }}"
  PACKER_CACHE_DIR: "{{ artifact_directory }}"
  PACKER_LOG: 1
  PACKER_LOG_PATH: "{{ artifact_directory }}/packerlog.txt"
active_config: "{{ build | selectattr('should_build', 'in', '[config,build]') | list }}" 
active_build: "{{ active_config | selectattr('should_build', 'eq', 'build') | map(attribute='packer_file.builders') | flatten | map(attribute='name') | list | join(',') }}"
active_build_dict: "{{ active_config | selectattr('should_build', 'eq', 'build') | list }}"
config_files: "{{ active_config | selectattr('files', 'defined') | map(attribute='files') | list | flatten | unique }}"
poll_value: 5
packer_variables: "{{ active_config | selectattr('packer_file.variables', 'defined') | map(attribute='packer_file.variables') | list | combine }}"
packer_sensitive_variables: "{{ active_config | selectattr('packer_file.sensitive-variables', 'defined') | map(attribute='packer_file.sensitive-variables') | list | flatten | unique }}"
packer_builders: "{{ active_config | selectattr('packer_file.builders', 'defined') | map(attribute='packer_file.builders') | list | flatten }}"
packer_provisioners: "{{ active_config | selectattr('packer_file.provisioners', 'defined') | map(attribute='packer_file.provisioners') | list | flatten }}"
packer_all:
  variables: "{{ packer_variables }}"
  sensitive-variables: "{{ packer_sensitive_variables }}"
  builders: "{{ packer_builders }}"
  provisioners: "{{ packer_provisioners }}"
ddmmyy: "{{ lookup('pipe','date +%d%m%y') }}"
