---
- hosts: build

  tasks:
  - name: Get the root certificate of Lets Encrypt
    get_url:
      url: https://censys.io/certificates/96bcec06264976f37460779acf28c5a7cfe8a3c0aae11a8ffcee05c0bddf08c6/pem/raw
      dest: /build_config/esxi_vsphere/rootca.pem

  - name: Enable bash shell on vcsa
    expect: 
      command: "sshpass -e ssh -oUserKnownHostsFile=/dev/null -oStrictHostKeyChecking=no root@{{ vcsa_build.vcenter_system_name }} 'shell'"
      responses:
        root.*: 
        - chsh -s /bin/bash root
        - exit 0
    vars:
      vcsa_build: "{{ vcsa_list[0] }}"
    environment:
      SSHPASS: "{{ vsphere.password }}"
    failed_when: false

  - name: Validate login worked
    command: "sshpass -e ssh-copy-id -oUserKnownHostsFile=/dev/null -oStrictHostKeyChecking=no root@{{ vcsa_build.vcenter_system_name }}"
    vars:
      vcsa_build: "{{ vcsa_list[0] }}"
    environment:
      SSHPASS: "{{ vsphere.password }}"

- hosts: vcsa

  tasks:
  - name: Copy TLS certificate and key
    copy:
      content: "{{ lookup('amazon.aws.aws_ssm', '/' + domain_name + '/' + item) }}"
      dest: "{{ item }}" 
    vars:
      domain_name: "{{ inventory_hostname.split('.')[1] + '.' + inventory_hostname.split('.')[2] }}"
    loop: 
    - "{{ inventory_hostname }}.pem"
    - "{{ inventory_hostname }}-fullchain.crt"

  - name: Get the root certificate of Lets Encrypt
    get_url:
      url: https://censys.io/certificates/96bcec06264976f37460779acf28c5a7cfe8a3c0aae11a8ffcee05c0bddf08c6/pem/raw
      dest: /root/esxi_vsphere/rootca.pem
