---
- hosts: vcsa
  user: root

  tasks:
  - name: Copy TLS certificate and key
    copy:
      content: "{{ lookup('amazon.aws.aws_ssm', '/' + domain_name + '/' + item) }}"
      dest: "{{ item }}" 
    vars:
      domain_name: "{{ inventory_hostname.split('.')[1] + '.' + inventory_hostname.split('.')[2] }}"
    loop: 
    - "{{ inventory_hostname }}.pem"
    - "{{ inventory_hostname }}-fullchain.crt"

  - name: Get the root certificate of Lets Encrypt
    get_url:
      url: https://censys.io/certificates/96bcec06264976f37460779acf28c5a7cfe8a3c0aae11a8ffcee05c0bddf08c6/pem/raw
      dest: /root/rootca.pem
